// This file is automatically generated by Script.py.

module EX_MEM(
    input         clk,
    input         rst,
    input  [31:0] EX_pc4,
    input  [31:0] EX_instr,
    input  [31:0] EX_aluDout,
    input  [31:0] EX_regDout1,
    input  [31:0] EX_regDout2,
    input  [31:0] EX_mdDoutHi,
    input  [31:0] EX_mdDoutLo,
    input         EX_memWrite,
    input         EX_memRead,
    input  [ 1:0] EX_memSize,
    input         EX_memSign,
    input         EX_regWrite,
    input  [ 1:0] EX_regAddr3Src,
    input  [ 2:0] EX_regDinSrc,
    input         EX_cp0Write,
    input  [ 1:0] EX_hlWrite,
    input         EX_hlDinHiSrc,
    input         EX_hlDinLoSrc,
    output [31:0] MEM_pc4,
    output [31:0] MEM_instr,
    output [31:0] MEM_aluDout,
    output [31:0] MEM_regDout1,
    output [31:0] MEM_regDout2,
    output [31:0] MEM_mdDoutHi,
    output [31:0] MEM_mdDoutLo,
    output        MEM_memWrite,
    output        MEM_memRead,
    output [ 1:0] MEM_memSize,
    output        MEM_memSign,
    output        MEM_regWrite,
    output [ 1:0] MEM_regAddr3Src,
    output [ 2:0] MEM_regDinSrc,
    output        MEM_cp0Write,
    output [ 1:0] MEM_hlWrite,
    output        MEM_hlDinHiSrc,
    output        MEM_hlDinLoSrc
);
    reg    [31:0] pc4Reg;
    reg    [31:0] instrReg;
    reg    [31:0] aluDoutReg;
    reg    [31:0] regDout1Reg;
    reg    [31:0] regDout2Reg;
    reg    [31:0] mdDoutHiReg;
    reg    [31:0] mdDoutLoReg;
    reg           memWriteReg;
    reg           memReadReg;
    reg    [ 1:0] memSizeReg;
    reg           memSignReg;
    reg           regWriteReg;
    reg    [ 1:0] regAddr3SrcReg;
    reg    [ 2:0] regDinSrcReg;
    reg           cp0WriteReg;
    reg    [ 1:0] hlWriteReg;
    reg           hlDinHiSrcReg;
    reg           hlDinLoSrcReg;

    always @ (posedge clk)
    begin
        if (rst)
        begin
            pc4Reg <= 32'bX;
            instrReg <= 32'bX;
            aluDoutReg <= 32'bX;
            regDout1Reg <= 32'bX;
            regDout2Reg <= 32'bX;
            mdDoutHiReg <= 32'bX;
            mdDoutLoReg <= 32'bX;
            memWriteReg <= 32'bX;
            memReadReg <= 32'bX;
            memSizeReg <= 32'bX;
            memSignReg <= 32'bX;
            regWriteReg <= 32'bX;
            regAddr3SrcReg <= 32'bX;
            regDinSrcReg <= 32'bX;
            cp0WriteReg <= 32'bX;
            hlWriteReg <= 32'bX;
            hlDinHiSrcReg <= 32'bX;
            hlDinLoSrcReg <= 32'bX;
        end
        else
        begin
            pc4Reg <= EX_pc4;
            instrReg <= EX_instr;
            aluDoutReg <= EX_aluDout;
            regDout1Reg <= EX_regDout1;
            regDout2Reg <= EX_regDout2;
            mdDoutHiReg <= EX_mdDoutHi;
            mdDoutLoReg <= EX_mdDoutLo;
            memWriteReg <= EX_memWrite;
            memReadReg <= EX_memRead;
            memSizeReg <= EX_memSize;
            memSignReg <= EX_memSign;
            regWriteReg <= EX_regWrite;
            regAddr3SrcReg <= EX_regAddr3Src;
            regDinSrcReg <= EX_regDinSrc;
            cp0WriteReg <= EX_cp0Write;
            hlWriteReg <= EX_hlWrite;
            hlDinHiSrcReg <= EX_hlDinHiSrc;
            hlDinLoSrcReg <= EX_hlDinLoSrc;
        end
    end

    assign MEM_pc4 = pc4Reg;
    assign MEM_instr = instrReg;
    assign MEM_aluDout = aluDoutReg;
    assign MEM_regDout1 = regDout1Reg;
    assign MEM_regDout2 = regDout2Reg;
    assign MEM_mdDoutHi = mdDoutHiReg;
    assign MEM_mdDoutLo = mdDoutLoReg;
    assign MEM_memWrite = memWriteReg;
    assign MEM_memRead = memReadReg;
    assign MEM_memSize = memSizeReg;
    assign MEM_memSign = memSignReg;
    assign MEM_regWrite = regWriteReg;
    assign MEM_regAddr3Src = regAddr3SrcReg;
    assign MEM_regDinSrc = regDinSrcReg;
    assign MEM_cp0Write = cp0WriteReg;
    assign MEM_hlWrite = hlWriteReg;
    assign MEM_hlDinHiSrc = hlDinHiSrcReg;
    assign MEM_hlDinLoSrc = hlDinLoSrcReg;

endmodule
