// This file is automatically generated by Script.py.

module ID_EX(
    input         clk,
    input         rst,
    input  [31:0] ID_pc4,
    input  [31:0] ID_instr,
    input  [ 3:0] ID_aluOp,
    input         ID_aluDin1Src,
    input         ID_aluDin2Src,
    input  [ 1:0] ID_mdOp,
    input         ID_memWrite,
    input         ID_memRead,
    input  [ 1:0] ID_memSize,
    input         ID_memSign,
    input         ID_regWrite,
    input  [ 1:0] ID_regAddr3Src,
    input  [ 2:0] ID_regDinSrc,
    input  [ 1:0] ID_hlWrite,
    input         ID_hlDinHiSrc,
    input         ID_hlDinLoSrc,
    input         ID_takeEret,
    output [31:0] EX_pc4,
    output [31:0] EX_instr,
    output [ 3:0] EX_aluOp,
    output        EX_aluDin1Src,
    output        EX_aluDin2Src,
    output [ 1:0] EX_mdOp,
    output        EX_memWrite,
    output        EX_memRead,
    output [ 1:0] EX_memSize,
    output        EX_memSign,
    output        EX_regWrite,
    output [ 1:0] EX_regAddr3Src,
    output [ 2:0] EX_regDinSrc,
    output [ 1:0] EX_hlWrite,
    output        EX_hlDinHiSrc,
    output        EX_hlDinLoSrc,
    output        EX_takeEret
);
    reg    [31:0] pc4Reg;
    reg    [31:0] instrReg;
    reg    [ 3:0] aluOpReg;
    reg           aluDin1SrcReg;
    reg           aluDin2SrcReg;
    reg    [ 1:0] mdOpReg;
    reg           memWriteReg;
    reg           memReadReg;
    reg    [ 1:0] memSizeReg;
    reg           memSignReg;
    reg           regWriteReg;
    reg    [ 1:0] regAddr3SrcReg;
    reg    [ 2:0] regDinSrcReg;
    reg    [ 1:0] hlWriteReg;
    reg           hlDinHiSrcReg;
    reg           hlDinLoSrcReg;
    reg           takeEretReg;

    always @ (posedge clk)
    begin
        if (rst)
        begin
            pc4Reg <= 32'bX;
            instrReg <= 32'bX;
            aluOpReg <= 32'bX;
            aluDin1SrcReg <= 32'bX;
            aluDin2SrcReg <= 32'bX;
            mdOpReg <= 32'bX;
            memWriteReg <= 32'bX;
            memReadReg <= 32'bX;
            memSizeReg <= 32'bX;
            memSignReg <= 32'bX;
            regWriteReg <= 32'bX;
            regAddr3SrcReg <= 32'bX;
            regDinSrcReg <= 32'bX;
            hlWriteReg <= 32'bX;
            hlDinHiSrcReg <= 32'bX;
            hlDinLoSrcReg <= 32'bX;
            takeEretReg <= 32'bX;
        end
        else
        begin
            pc4Reg <= ID_pc4;
            instrReg <= ID_instr;
            aluOpReg <= ID_aluOp;
            aluDin1SrcReg <= ID_aluDin1Src;
            aluDin2SrcReg <= ID_aluDin2Src;
            mdOpReg <= ID_mdOp;
            memWriteReg <= ID_memWrite;
            memReadReg <= ID_memRead;
            memSizeReg <= ID_memSize;
            memSignReg <= ID_memSign;
            regWriteReg <= ID_regWrite;
            regAddr3SrcReg <= ID_regAddr3Src;
            regDinSrcReg <= ID_regDinSrc;
            hlWriteReg <= ID_hlWrite;
            hlDinHiSrcReg <= ID_hlDinHiSrc;
            hlDinLoSrcReg <= ID_hlDinLoSrc;
            takeEretReg <= ID_takeEret;
        end
    end

    assign EX_pc4 = pc4Reg;
    assign EX_instr = instrReg;
    assign EX_aluOp = aluOpReg;
    assign EX_aluDin1Src = aluDin1SrcReg;
    assign EX_aluDin2Src = aluDin2SrcReg;
    assign EX_mdOp = mdOpReg;
    assign EX_memWrite = memWriteReg;
    assign EX_memRead = memReadReg;
    assign EX_memSize = memSizeReg;
    assign EX_memSign = memSignReg;
    assign EX_regWrite = regWriteReg;
    assign EX_regAddr3Src = regAddr3SrcReg;
    assign EX_regDinSrc = regDinSrcReg;
    assign EX_hlWrite = hlWriteReg;
    assign EX_hlDinHiSrc = hlDinHiSrcReg;
    assign EX_hlDinLoSrc = hlDinLoSrcReg;
    assign EX_takeEret = takeEretReg;

endmodule
