// This file is automatically generated by Script.py.

module IF_ID(
    input         clk,
    input         rst,
    input         flush,
    input         stall,
    input  [31:0] IF_pc4,
    input  [31:0] IF_instr,
    output [31:0] ID_pc4,
    output [31:0] ID_instr
);
    reg    [31:0] pc4Reg;
    reg    [31:0] instrReg;

    always @ (posedge clk)
    begin
        if (rst)
            pc4Reg <= 0;
        if (rst || flush)
        begin
            instrReg <= 0;
        end
        else if (!stall)
        begin
            pc4Reg <= IF_pc4;
            instrReg <= IF_instr;
        end
    end

    assign ID_pc4 = pc4Reg;
    assign ID_instr = instrReg;

endmodule
