// This file is automatically generated by Script.py.

module MEM_WB(
    input         clk,
    input         rst,
    input  [31:0] MEM_pc4,
    input  [31:0] MEM_instr,
    input         MEM_regWrite,
    input  [ 1:0] MEM_regAddr3Src,
    input  [ 2:0] MEM_regDinSrc,
    input  [ 1:0] MEM_hlWrite,
    input         MEM_hlDinHiSrc,
    input         MEM_hlDinLoSrc,
    input         MEM_takeEret,
    output [31:0] WB_pc4,
    output [31:0] WB_instr,
    output        WB_regWrite,
    output [ 1:0] WB_regAddr3Src,
    output [ 2:0] WB_regDinSrc,
    output [ 1:0] WB_hlWrite,
    output        WB_hlDinHiSrc,
    output        WB_hlDinLoSrc,
    output        WB_takeEret
);
    reg    [31:0] pc4Reg;
    reg    [31:0] instrReg;
    reg           regWriteReg;
    reg    [ 1:0] regAddr3SrcReg;
    reg    [ 2:0] regDinSrcReg;
    reg    [ 1:0] hlWriteReg;
    reg           hlDinHiSrcReg;
    reg           hlDinLoSrcReg;
    reg           takeEretReg;

    always @ (posedge clk)
    begin
        if (rst)
        begin
            pc4Reg <= 32'bX;
            instrReg <= 32'bX;
            regWriteReg <= 32'bX;
            regAddr3SrcReg <= 32'bX;
            regDinSrcReg <= 32'bX;
            hlWriteReg <= 32'bX;
            hlDinHiSrcReg <= 32'bX;
            hlDinLoSrcReg <= 32'bX;
            takeEretReg <= 32'bX;
        end
        else
        begin
            pc4Reg <= MEM_pc4;
            instrReg <= MEM_instr;
            regWriteReg <= MEM_regWrite;
            regAddr3SrcReg <= MEM_regAddr3Src;
            regDinSrcReg <= MEM_regDinSrc;
            hlWriteReg <= MEM_hlWrite;
            hlDinHiSrcReg <= MEM_hlDinHiSrc;
            hlDinLoSrcReg <= MEM_hlDinLoSrc;
            takeEretReg <= MEM_takeEret;
        end
    end

    assign WB_pc4 = pc4Reg;
    assign WB_instr = instrReg;
    assign WB_regWrite = regWriteReg;
    assign WB_regAddr3Src = regAddr3SrcReg;
    assign WB_regDinSrc = regDinSrcReg;
    assign WB_hlWrite = hlWriteReg;
    assign WB_hlDinHiSrc = hlDinHiSrcReg;
    assign WB_hlDinLoSrc = hlDinLoSrcReg;
    assign WB_takeEret = takeEretReg;

endmodule
