// This file is automatically generated by Script.py.

module Control(
    input  [31:0] instr,
    output        DelaySlot,
    output        BraEnable,
    output [ 2:0] BraOp,
    output        TakeJumpImm,
    output        TakeJumpReg,
    output        ExtSign,
    output [ 1:0] RegAddr3Src,
    output [ 3:0] AluOp,
    output        AluDin1Src,
    output        AluDin2Src,
    output [ 1:0] MdOp,
    output        MemWrite,
    output        MemRead,
    output [ 1:0] MemSize,
    output        MemSign,
    output        RegWrite,
    output [ 2:0] RegDinSrc,
    output        Cp0Write,
    output [ 1:0] HlWrite,
    output        HlDinHiSrc,
    output        HlDinLoSrc,
    output        TakeEret,
    output [ 1:0] Exception
);
    assign {DelaySlot, BraEnable, BraOp, TakeJumpImm, TakeJumpReg, ExtSign, RegAddr3Src, AluOp, AluDin1Src, AluDin2Src, MdOp, MemWrite, MemRead, MemSize, MemSign, RegWrite, RegDinSrc, Cp0Write, HlWrite, HlDinHiSrc, HlDinLoSrc, TakeEret, Exception} =
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100000 ? 35'b0_0_XXX_0_0_X_00_0000_0_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // add
        instr[31:26] == 6'b001000                                                                                                                                           ? 35'b0_0_XXX_0_0_1_01_0000_0_1_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // addi
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100001 ? 35'b0_0_XXX_0_0_X_00_0001_0_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // addu
        instr[31:26] == 6'b001001                                                                                                                                           ? 35'b0_0_XXX_0_0_1_01_0001_0_1_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // addiu
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100010 ? 35'b0_0_XXX_0_0_X_00_0010_0_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // sub
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100011 ? 35'b0_0_XXX_0_0_X_00_0011_0_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // subu
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b101010 ? 35'b0_0_XXX_0_0_X_00_0100_0_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // slt
        instr[31:26] == 6'b001010                                                                                                                                           ? 35'b0_0_XXX_0_0_1_01_0100_0_1_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // slti
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b101011 ? 35'b0_0_XXX_0_0_X_00_0101_0_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // sltu
        instr[31:26] == 6'b001011                                                                                                                                           ? 35'b0_0_XXX_0_0_1_01_0101_0_1_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // sltiu
        instr[31:26] == 6'b000000                                                         && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b011010 ? 35'b0_0_XXX_0_0_X_XX_1110_X_X_00_0_0_XX_X_0_XXX_0_11_0_0_0_00 : // div
        instr[31:26] == 6'b000000                                                         && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b011011 ? 35'b0_0_XXX_0_0_X_XX_1110_X_X_01_0_0_XX_X_0_XXX_0_11_0_0_0_00 : // divu
        instr[31:26] == 6'b000000                                                         && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b011000 ? 35'b0_0_XXX_0_0_X_XX_1110_X_X_10_0_0_XX_X_0_XXX_0_11_0_0_0_00 : // mult
        instr[31:26] == 6'b000000                                                         && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b011001 ? 35'b0_0_XXX_0_0_X_XX_1110_X_X_11_0_0_XX_X_0_XXX_0_11_0_0_0_00 : // multu
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100100 ? 35'b0_0_XXX_0_0_X_00_0110_0_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // and
        instr[31:26] == 6'b001100                                                                                                                                           ? 35'b0_0_XXX_0_0_0_01_0110_0_1_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // andi
        instr[31:26] == 6'b001111 && instr[25:21] == 5'b00000                                                                                                               ? 35'b0_0_XXX_0_0_X_01_0111_X_1_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // lui
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100111 ? 35'b0_0_XXX_0_0_X_00_1000_0_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // nor
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100101 ? 35'b0_0_XXX_0_0_X_00_1001_0_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // or
        instr[31:26] == 6'b001101                                                                                                                                           ? 35'b0_0_XXX_0_0_0_01_1001_0_1_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // ori
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100110 ? 35'b0_0_XXX_0_0_X_00_1010_0_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // xor
        instr[31:26] == 6'b001110                                                                                                                                           ? 35'b0_0_XXX_0_0_0_01_1010_0_1_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // xori
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b000100 ? 35'b0_0_XXX_0_0_X_00_1011_0_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // sllv
        instr[31:26] == 6'b000000 && instr[25:21] == 5'b00000                                                                                    && instr[5:0] == 6'b000000 ? 35'b0_0_XXX_0_0_X_00_1011_1_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // sll
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b000111 ? 35'b0_0_XXX_0_0_X_00_1100_0_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // srav
        instr[31:26] == 6'b000000 && instr[25:21] == 5'b00000                                                                                    && instr[5:0] == 6'b000011 ? 35'b0_0_XXX_0_0_X_00_1100_1_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // sra
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b000110 ? 35'b0_0_XXX_0_0_X_00_1101_0_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // srlv
        instr[31:26] == 6'b000000 && instr[25:21] == 5'b00000                                                                                    && instr[5:0] == 6'b000010 ? 35'b0_0_XXX_0_0_X_00_1101_1_0_XX_0_0_XX_X_1_000_0_00_X_X_0_00 : // srl
        instr[31:26] == 6'b000100                                                                                                                                           ? 35'b1_1_000_0_0_1_XX_1110_X_X_XX_0_0_XX_X_0_XXX_0_00_X_X_0_00 : // beq
        instr[31:26] == 6'b000101                                                                                                                                           ? 35'b1_1_001_0_0_1_XX_1110_X_X_XX_0_0_XX_X_0_XXX_0_00_X_X_0_00 : // bne
        instr[31:26] == 6'b000001                             && instr[20:16] == 5'b00001                                                                                   ? 35'b1_1_010_0_0_1_XX_1110_X_X_XX_0_0_XX_X_0_XXX_0_00_X_X_0_00 : // bgez
        instr[31:26] == 6'b000111                             && instr[20:16] == 5'b00000                                                                                   ? 35'b1_1_011_0_0_1_XX_1110_X_X_XX_0_0_XX_X_0_XXX_0_00_X_X_0_00 : // bgtz
        instr[31:26] == 6'b000110                             && instr[20:16] == 5'b00000                                                                                   ? 35'b1_1_100_0_0_1_XX_1110_X_X_XX_0_0_XX_X_0_XXX_0_00_X_X_0_00 : // blez
        instr[31:26] == 6'b000001                             && instr[20:16] == 5'b00000                                                                                   ? 35'b1_1_101_0_0_1_XX_1110_X_X_XX_0_0_XX_X_0_XXX_0_00_X_X_0_00 : // bltz
        instr[31:26] == 6'b000001                             && instr[20:16] == 5'b10001                                                                                   ? 35'b1_1_010_0_0_1_10_1110_X_X_XX_0_0_XX_X_1_001_0_00_X_X_0_00 : // bgezal
        instr[31:26] == 6'b000001                             && instr[20:16] == 5'b10000                                                                                   ? 35'b1_1_101_0_0_1_10_1110_X_X_XX_0_0_XX_X_1_001_0_00_X_X_0_00 : // bltzal
        instr[31:26] == 6'b000010                                                                                                                                           ? 35'b1_0_XXX_1_0_X_XX_1110_X_X_XX_0_0_XX_X_0_XXX_0_00_X_X_0_00 : // j
        instr[31:26] == 6'b000011                                                                                                                                           ? 35'b1_0_XXX_1_0_X_10_1110_X_X_XX_0_0_XX_X_1_001_0_00_X_X_0_00 : // jal
        instr[31:26] == 6'b000000                             && instr[20:16] == 5'b00000 && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b001000 ? 35'b1_0_XXX_0_1_X_XX_1110_X_X_XX_0_0_XX_X_0_XXX_0_00_X_X_0_00 : // jr
        instr[31:26] == 6'b000000                             && instr[20:16] == 5'b00000                             && instr[10:6] == 5'b00000 && instr[5:0] == 6'b001001 ? 35'b1_0_XXX_0_1_X_00_1110_X_X_XX_0_0_XX_X_1_001_0_00_X_X_0_00 : // jalr
        instr[31:26] == 6'b000000 && instr[25:21] == 5'b00000 && instr[20:16] == 5'b00000                             && instr[10:6] == 5'b00000 && instr[5:0] == 6'b010000 ? 35'b0_0_XXX_0_0_X_00_1110_X_X_XX_0_0_XX_X_1_010_0_00_X_X_0_00 : // mfhi
        instr[31:26] == 6'b000000 && instr[25:21] == 5'b00000 && instr[20:16] == 5'b00000                             && instr[10:6] == 5'b00000 && instr[5:0] == 6'b010010 ? 35'b0_0_XXX_0_0_X_00_1110_X_X_XX_0_0_XX_X_1_011_0_00_X_X_0_00 : // mflo
        instr[31:26] == 6'b000000                             && instr[20:16] == 5'b00000 && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b010001 ? 35'b0_0_XXX_0_0_X_XX_1110_X_X_XX_0_0_XX_X_0_XXX_0_10_1_X_0_00 : // mthi
        instr[31:26] == 6'b000000                             && instr[20:16] == 5'b00000 && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b010011 ? 35'b0_0_XXX_0_0_X_XX_1110_X_X_XX_0_0_XX_X_0_XXX_0_01_X_1_0_00 : // mtlo
        instr[31:26] == 6'b000000                                                                                                                && instr[5:0] == 6'b001101 ? 35'b0_0_XXX_0_0_X_XX_1110_X_X_XX_0_0_XX_X_0_XXX_0_00_X_X_0_01 : // break
        instr[31:26] == 6'b000000                                                                                                                && instr[5:0] == 6'b001100 ? 35'b0_0_XXX_0_0_X_XX_1110_X_X_XX_0_0_XX_X_0_XXX_0_00_X_X_0_10 : // syscall
        instr[31:26] == 6'b100000                                                                                                                                           ? 35'b0_0_XXX_0_0_1_01_0001_0_1_XX_0_1_00_1_1_100_0_00_X_X_0_00 : // lb
        instr[31:26] == 6'b100100                                                                                                                                           ? 35'b0_0_XXX_0_0_1_01_0001_0_1_XX_0_1_00_0_1_100_0_00_X_X_0_00 : // lbu
        instr[31:26] == 6'b100001                                                                                                                                           ? 35'b0_0_XXX_0_0_1_01_0001_0_1_XX_0_1_01_1_1_100_0_00_X_X_0_00 : // lh
        instr[31:26] == 6'b100101                                                                                                                                           ? 35'b0_0_XXX_0_0_1_01_0001_0_1_XX_0_1_01_0_1_100_0_00_X_X_0_00 : // lhu
        instr[31:26] == 6'b100011                                                                                                                                           ? 35'b0_0_XXX_0_0_1_01_0001_0_1_XX_0_1_10_X_1_100_0_00_X_X_0_00 : // lw
        instr[31:26] == 6'b101000                                                                                                                                           ? 35'b0_0_XXX_0_0_1_XX_0001_0_1_XX_1_0_00_X_0_XXX_0_00_X_X_0_00 : // sb
        instr[31:26] == 6'b101001                                                                                                                                           ? 35'b0_0_XXX_0_0_1_XX_0001_0_1_XX_1_0_01_X_0_XXX_0_00_X_X_0_00 : // sh
        instr[31:26] == 6'b101011                                                                                                                                           ? 35'b0_0_XXX_0_0_1_XX_0001_0_1_XX_1_0_10_X_0_XXX_0_00_X_X_0_00 : // sw
        instr[31:26] == 6'b010000 && instr[25:21] == 5'b10000 && instr[20:16] == 5'b00000 && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b011000 ? 35'b0_0_XXX_0_0_X_XX_1110_X_X_XX_0_0_XX_X_0_XXX_0_00_X_X_1_00 : // eret
        instr[31:26] == 6'b010000 && instr[25:21] == 5'b00000                                                         && instr[10:6] == 5'b00000                            ? 35'b0_0_XXX_0_0_X_01_1110_X_X_XX_0_0_XX_X_1_101_0_00_X_X_0_00 : // mfc0
        instr[31:26] == 6'b010000 && instr[25:21] == 5'b00100                                                         && instr[10:6] == 5'b00000                            ? 35'b0_0_XXX_0_0_X_XX_1110_X_X_XX_0_0_XX_X_0_XXX_1_00_X_X_0_00 : // mtc0
                                                                                                                                                                              35'b0_0_XXX_0_0_X_XX_1110_X_X_XX_0_0_XX_X_0_XXX_0_00_X_X_0_11 ; // unknown

endmodule
