// This file is automatically generated by Script.py.

module Control(
    input  [31:0] instr,
    output        BraEnable,
    output [ 2:0] BraOp,
    output        TakeJumpImm,
    output        TakeJumpReg,
    output        ExtSign,
    output [ 3:0] AluOp,
    output        AluDin1Src,
    output        AluDin2Src,
    output [ 1:0] MdOp,
    output        MemWrite,
    output        MemRead,
    output [ 1:0] MemSize,
    output        MemSign,
    output        RegWrite,
    output [ 1:0] RegAddr3Src,
    output [ 2:0] RegDinSrc,
    output [ 1:0] HlWrite,
    output        HlDinHiSrc,
    output        HlDinLoSrc,
    output        TakeEret,
    output        exception
);
    assign {BraEnable, BraOp, TakeJumpImm, TakeJumpReg, ExtSign, AluOp, AluDin1Src, AluDin2Src, MdOp, MemWrite, MemRead, MemSize, MemSign, RegWrite, RegAddr3Src, RegDinSrc, HlWrite, HlDinHiSrc, HlDinLoSrc, TakeEret, exception} =
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100000 ? 32'b0_XXX_0_0_X_0000_0_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // add
        instr[31:26] == 6'b001000                                                                                                                                           ? 32'b0_XXX_0_0_1_0000_0_1_XX_0_0_XX_X_1_01_000_00_X_X_0_0 : // addi
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100001 ? 32'b0_XXX_0_0_X_0001_0_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // addu
        instr[31:26] == 6'b001001                                                                                                                                           ? 32'b0_XXX_0_0_1_0001_0_1_XX_0_0_XX_X_1_01_000_00_X_X_0_0 : // addiu
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100010 ? 32'b0_XXX_0_0_X_0010_0_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // sub
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100011 ? 32'b0_XXX_0_0_X_0011_0_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // subu
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b101010 ? 32'b0_XXX_0_0_X_0100_0_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // slt
        instr[31:26] == 6'b001010                                                                                                                                           ? 32'b0_XXX_0_0_1_0100_0_1_XX_0_0_XX_X_1_01_000_00_X_X_0_0 : // slti
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b101011 ? 32'b0_XXX_0_0_X_0101_0_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // sltu
        instr[31:26] == 6'b001011                                                                                                                                           ? 32'b0_XXX_0_0_1_0101_0_1_XX_0_0_XX_X_1_01_000_00_X_X_0_0 : // sltiu
        instr[31:26] == 6'b000000                                                         && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b011010 ? 32'b0_XXX_0_0_X_XXXX_X_X_00_0_0_XX_X_0_XX_XXX_11_0_0_0_0 : // div
        instr[31:26] == 6'b000000                                                         && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b011011 ? 32'b0_XXX_0_0_X_XXXX_X_X_01_0_0_XX_X_0_XX_XXX_11_0_0_0_0 : // divu
        instr[31:26] == 6'b000000                                                         && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b011000 ? 32'b0_XXX_0_0_X_XXXX_X_X_10_0_0_XX_X_0_XX_XXX_11_0_0_0_0 : // mult
        instr[31:26] == 6'b000000                                                         && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b011001 ? 32'b0_XXX_0_0_X_XXXX_X_X_11_0_0_XX_X_0_XX_XXX_11_0_0_0_0 : // multu
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100100 ? 32'b0_XXX_0_0_X_0110_0_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // and
        instr[31:26] == 6'b001100                                                                                                                                           ? 32'b0_XXX_0_0_0_0110_0_1_XX_0_0_XX_X_1_01_000_00_X_X_0_0 : // andi
        instr[31:26] == 6'b001111 && instr[25:21] == 5'b00000                                                                                                               ? 32'b0_XXX_0_0_X_0111_X_1_XX_0_0_XX_X_1_01_000_00_X_X_0_0 : // lui
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100111 ? 32'b0_XXX_0_0_X_1000_0_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // nor
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100101 ? 32'b0_XXX_0_0_X_1001_0_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // or
        instr[31:26] == 6'b001101                                                                                                                                           ? 32'b0_XXX_0_0_0_1001_0_1_XX_0_0_XX_X_1_01_000_00_X_X_0_0 : // ori
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b100110 ? 32'b0_XXX_0_0_X_1010_0_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // xor
        instr[31:26] == 6'b001110                                                                                                                                           ? 32'b0_XXX_0_0_0_1010_0_1_XX_0_0_XX_X_1_01_000_00_X_X_0_0 : // xori
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b000100 ? 32'b0_XXX_0_0_X_1011_0_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // sllv
        instr[31:26] == 6'b000000 && instr[25:21] == 5'b00000                                                                                    && instr[5:0] == 6'b000000 ? 32'b0_XXX_0_0_X_1011_1_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // sll
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b000111 ? 32'b0_XXX_0_0_X_1100_0_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // srav
        instr[31:26] == 6'b000000 && instr[25:21] == 5'b00000                                                                                    && instr[5:0] == 6'b000011 ? 32'b0_XXX_0_0_X_1100_1_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // sra
        instr[31:26] == 6'b000000                                                                                     && instr[10:6] == 5'b00000 && instr[5:0] == 6'b000110 ? 32'b0_XXX_0_0_X_1101_0_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // srlv
        instr[31:26] == 6'b000000 && instr[25:21] == 5'b00000                                                                                    && instr[5:0] == 6'b000010 ? 32'b0_XXX_0_0_X_1101_1_0_XX_0_0_XX_X_1_00_000_00_X_X_0_0 : // srl
        instr[31:26] == 6'b000100                                                                                                                                           ? 32'b1_000_0_0_1_XXXX_X_X_XX_0_0_XX_X_0_XX_XXX_00_X_X_0_0 : // beq
        instr[31:26] == 6'b000101                                                                                                                                           ? 32'b1_001_0_0_1_XXXX_X_X_XX_0_0_XX_X_0_XX_XXX_00_X_X_0_0 : // bne
        instr[31:26] == 6'b000001                             && instr[20:16] == 5'b00001                                                                                   ? 32'b1_010_0_0_1_XXXX_X_X_XX_0_0_XX_X_0_XX_XXX_00_X_X_0_0 : // bgez
        instr[31:26] == 6'b000111                             && instr[20:16] == 5'b00000                                                                                   ? 32'b1_011_0_0_1_XXXX_X_X_XX_0_0_XX_X_0_XX_XXX_00_X_X_0_0 : // bgtz
        instr[31:26] == 6'b000110                             && instr[20:16] == 5'b00000                                                                                   ? 32'b1_100_0_0_1_XXXX_X_X_XX_0_0_XX_X_0_XX_XXX_00_X_X_0_0 : // blez
        instr[31:26] == 6'b000001                             && instr[20:16] == 5'b00000                                                                                   ? 32'b1_101_0_0_1_XXXX_X_X_XX_0_0_XX_X_0_XX_XXX_00_X_X_0_0 : // bltz
        instr[31:26] == 6'b000001                             && instr[20:16] == 5'b10001                                                                                   ? 32'b1_010_0_0_1_XXXX_X_X_XX_0_0_XX_X_1_10_001_00_X_X_0_0 : // bgezal
        instr[31:26] == 6'b000001                             && instr[20:16] == 5'b10000                                                                                   ? 32'b1_101_0_0_1_XXXX_X_X_XX_0_0_XX_X_1_10_001_00_X_X_0_0 : // bltzal
        instr[31:26] == 6'b000010                                                                                                                                           ? 32'b0_XXX_1_0_X_XXXX_X_X_XX_0_0_XX_X_0_XX_XXX_00_X_X_0_0 : // j
        instr[31:26] == 6'b000011                                                                                                                                           ? 32'b0_XXX_1_0_X_XXXX_X_X_XX_0_0_XX_X_1_10_001_00_X_X_0_0 : // jal
        instr[31:26] == 6'b000000                             && instr[20:16] == 5'b00000 && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b001000 ? 32'b0_XXX_0_1_X_XXXX_X_X_XX_0_0_XX_X_0_XX_XXX_00_X_X_0_0 : // jr
        instr[31:26] == 6'b000000                             && instr[20:16] == 5'b00000                             && instr[10:6] == 5'b00000 && instr[5:0] == 6'b001001 ? 32'b0_XXX_0_1_X_XXXX_X_X_XX_0_0_XX_X_1_00_001_00_X_X_0_0 : // jalr
        instr[31:26] == 6'b000000 && instr[25:21] == 5'b00000 && instr[20:16] == 5'b00000                             && instr[10:6] == 5'b00000 && instr[5:0] == 6'b010000 ? 32'b0_XXX_0_0_X_XXXX_X_X_XX_0_0_XX_X_1_00_010_00_X_X_0_0 : // mfhi
        instr[31:26] == 6'b000000 && instr[25:21] == 5'b00000 && instr[20:16] == 5'b00000                             && instr[10:6] == 5'b00000 && instr[5:0] == 6'b010010 ? 32'b0_XXX_0_0_X_XXXX_X_X_XX_0_0_XX_X_1_00_011_00_X_X_0_0 : // mflo
        instr[31:26] == 6'b000000                             && instr[20:16] == 5'b00000 && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b010001 ? 32'b0_XXX_0_0_X_XXXX_X_X_XX_0_0_XX_X_0_XX_XXX_10_1_X_0_0 : // mthi
        instr[31:26] == 6'b000000                             && instr[20:16] == 5'b00000 && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b010011 ? 32'b0_XXX_0_0_X_XXXX_X_X_XX_0_0_XX_X_0_XX_XXX_01_X_1_0_0 : // mtlo
        instr[31:26] == 6'b000000                                                                                                                && instr[5:0] == 6'b001101 ? 32'b0_XXX_0_0_X_XXXX_X_X_XX_0_0_XX_X_0_XX_XXX_00_X_X_0_0 : // break
        instr[31:26] == 6'b000000                                                                                                                && instr[5:0] == 6'b001100 ? 32'b0_XXX_0_0_X_XXXX_X_X_XX_0_0_XX_X_0_XX_XXX_00_X_X_0_0 : // syscall
        instr[31:26] == 6'b100000                                                                                                                                           ? 32'b0_XXX_0_0_1_0001_0_1_XX_0_1_00_1_1_01_100_00_X_X_0_0 : // lb
        instr[31:26] == 6'b100100                                                                                                                                           ? 32'b0_XXX_0_0_1_0001_0_1_XX_0_1_00_0_1_01_100_00_X_X_0_0 : // lbu
        instr[31:26] == 6'b100001                                                                                                                                           ? 32'b0_XXX_0_0_1_0001_0_1_XX_0_1_01_1_1_01_100_00_X_X_0_0 : // lh
        instr[31:26] == 6'b100101                                                                                                                                           ? 32'b0_XXX_0_0_1_0001_0_1_XX_0_1_01_0_1_01_100_00_X_X_0_0 : // lhu
        instr[31:26] == 6'b100011                                                                                                                                           ? 32'b0_XXX_0_0_1_0001_0_1_XX_0_1_10_X_1_01_100_00_X_X_0_0 : // lw
        instr[31:26] == 6'b101000                                                                                                                                           ? 32'b0_XXX_0_0_1_0001_0_1_XX_1_0_00_X_0_XX_XXX_00_X_X_0_0 : // sb
        instr[31:26] == 6'b101001                                                                                                                                           ? 32'b0_XXX_0_0_1_0001_0_1_XX_1_0_01_X_0_XX_XXX_00_X_X_0_0 : // sh
        instr[31:26] == 6'b101011                                                                                                                                           ? 32'b0_XXX_0_0_1_0001_0_1_XX_1_0_10_X_0_XX_XXX_00_X_X_0_0 : // sw
        instr[31:26] == 6'b010000 && instr[25:21] == 5'b10000 && instr[20:16] == 5'b00000 && instr[15:11] == 5'b00000 && instr[10:6] == 5'b00000 && instr[5:0] == 6'b011000 ? 32'b0_XXX_0_0_X_XXXX_X_X_XX_0_0_XX_X_0_XX_XXX_00_X_X_1_0 : // eret
        instr[31:26] == 6'b010000 && instr[25:21] == 5'b00000                                                         && instr[10:6] == 5'b00000                            ? 32'b0_XXX_0_0_X_XXXX_X_X_XX_0_0_XX_X_1_01_101_00_X_X_0_0 : // mfc0
        instr[31:26] == 6'b010000 && instr[25:21] == 5'b00100                                                         && instr[10:6] == 5'b00000                            ? 32'b0_XXX_0_0_X_XXXX_X_X_XX_0_0_XX_X_0_XX_XXX_00_X_X_0_0 : // mtc0
                                                                                                                                                                              32'bX_XXX_X_X_X_XXXX_X_X_XX_X_X_XX_X_X_XX_XXX_XX_X_X_X_1 ; // exception

endmodule
